// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2oUtvKCKK9UjFBZgvRtZUoL420NS9eJ8',
    appId: '1:532478371882:web:156e311e9088139ae7fb53',
    messagingSenderId: '532478371882',
    projectId: 'fleet-tracker-9242a',
    authDomain: 'fleet-tracker-9242a.firebaseapp.com',
    storageBucket: 'fleet-tracker-9242a.firebasestorage.app',
    measurementId: 'G-YDK9QG534J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgd-ULi4YjnekQPlg0zWZZPvPuYc0pB28',
    appId: '1:532478371882:android:392fa2ead53486c1e7fb53',
    messagingSenderId: '532478371882',
    projectId: 'fleet-tracker-9242a',
    storageBucket: 'fleet-tracker-9242a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr75VkBt7sXJrN17gEIjW3lHlBOqSJuMc',
    appId: '1:532478371882:ios:89c256c5f97861e3e7fb53',
    messagingSenderId: '532478371882',
    projectId: 'fleet-tracker-9242a',
    storageBucket: 'fleet-tracker-9242a.firebasestorage.app',
    iosBundleId: 'com.vehicletracker.vehicleMaintenanceTracker',
  );
}
